COSMIC-PopSynth/COSMIC

bin/runFixedPop
cosmic/Match.py
cosmic/tests/test_match.py

also cleaned up unnecessary imports in runFixedPop

Short period convergence

---

cosmic/evolve.py
cosmic/src/comenv.f
cosmic/src/concatkstars.f
cosmic/src/const_bse.h
cosmic/src/evolv2.f
setup.py

@katiebreivik this is a pretty good start to address the new logic mentioned in #88 #87 
Things to check I think is that we are really capturing all the times the system gets disrupted, from all my mucking about and changing of `bin_state` before separating `bin_state` and `merger_type` I am not 100 percent sure. Also I believe when `bin_state = 2`  gets set I have reset `mergertype=-1` in all those situations.

WIP: Update bin state

---

cosmic/evolve.py

Changing column names

---

bin/runFixedPop
cosmic/Match.py
cosmic/gxreal.py
cosmic/sample/initialbinarytable.py
cosmic/utils.py
docs/examples/index.rst
docs/fixedpop/index.rst
docs/runpop/index.rst
examples/Params.ini

@michaelzevin found that the total mass was being written to the dat file multiple times. This is a very simple PR that fixes this [issue](https://github.com/COSMIC-PopSynth/COSMIC/issues/114).

Total mass write

---

examples/Params.ini

Made the params file look dope AF. Removed merger flag, added more info, and wrote defaults for each parameter

Updated example Params.ini file

---

cosmic/FIRE.py
cosmic/sample/sampler/independent.py
cosmic/sample/sampler/multidim.py
cosmic/utils.py

High res mw

---

cosmic/src/bse.f
cosmic/src/comenv.f
cosmic/src/evolv2.f
cosmic/src/popbinb.f
cosmic/src/popbintd.f

fixed ceflag to only take values of 0 and 1. changed the logic of ceflag in comenv to make the use of this flag more clear

updates to CE flag

---

cosmic/utils.py

making min_max_mass select be able to handle more than two kstar valu…es in the event that the user specifies a full range of kstars instead of a minimum and maximum

min_max_mass selection fix

---

cosmic/sample/sampler/independent.py
cosmic/tests/test_sample.py

added in a line that takes the maximum and the eccentricity factor needed to compute the Roche Lobe for an eccentric system

Fix for issue #193

---

cosmic/evolve.py
cosmic/src/bpp_array.f
cosmic/src/const_bse.h
cosmic/src/evolv2.f

I added the columns needed in #215.

Added extra columns to the BPP array.

---

bin/runFixedPop
cosmic/evolve.py
cosmic/src/kick.f
cosmic/utils.py
examples/Params.ini

Added function in utils.py that checks that the values supplied in the BSEDict are viable. This function is called in both evolve and runFixedPop.

Flag checks

---

bin/runFixedPop
cosmic/sample/sampler/independent.py
cosmic/sample/sampler/multidim.py
cosmic/src/bpp_array.f

changing all units to match those in the docs, the main changes are to make all log10 values not log10 and to write the orbital period as days

units overhaul

---

cosmic/src/hrdiag.f
cosmic/utils.py
examples/Params.ini

Updated the Spera+Mapelli PISN prescriptions; added 8th order polynomial fits to table 1 in Marchant 2018 and table 5 in Woosley 2019.

Pisn edits

---

cosmic/src/evolv2.f

This was a silly mistake on my end!

adding in missed cases for kstar=4 and kstar=7

---

docs/examples/index.rst

This is a very simple docs PR that fixes this issue: https://github.com/COSMIC-PopSynth/COSMIC/issues/294

Docs for issue #249

---

docs/inifile/index.rst

Convergence doc patch 2.0

---

cosmic/src/hrdiag.f

Should be a simple one, just changed the coefficients. Here's a plot that Michael made with the new coefficients:

fixed coefificients for the Marchant PPISN prescription

---

cosmic/sample/sampler/independent.py
cosmic/tests/test_sample.py

I implemented a Kroupa 2001 (https://arxiv.org/abs/astro-ph/0009005) sampler to independent.py, nearly identical to the Kroupa 1993 sampler already implemented. I also implemented the corresponding consistency test in test_sample.py

Kroupa01 Sampler

---

cosmic/evolve.py
cosmic/src/const_bse.h

Made the common block do what it's supposed to

Fixed Common block nightmare

---

cosmic/utils.py

adding in catch for single stars

---

examples/Params.ini

there were a couple flags that were updated in the docs but not params.ini

Tiny params.ini patch

---

cosmic/tests/test_utils.py
cosmic/utils.py

very tiny pr that addresses this issue: #349

changing lower mass limits for exploding stars

---

bin/cosmic-pop
cosmic/Match.py
cosmic/tests/test_utils.py
cosmic/utils.py
examples/Params.ini

First two commits get #364 and #361. Will add in #355 in a couple of mins!

Issue 364, 361, 355

---

cosmic/utils.py

so that it performs correctly in instan…ces where dtp is set such that there are multiple entries in the bcm array

fixed the binary state filter 

---

cosmic/sample/sampler/independent.py
cosmic/tests/test_sample.py

allows for eccentricity=0.0 in the initial conditions now

Circ init c

---

cosmic/evolve.py
cosmic/sample/sampler/cmc.py
cosmic/src/benchmarkevolv2.f
cosmic/src/comenv.f
cosmic/src/evolv2.f
cosmic/src/kick.f

Adding back in bkick as minimally as possible to maintain compatbility with CMC, it really is not a big annoyance

---

bin/cosmic-pop

tiny hotfix to add qmin in the independent sampler call in cosmic-pop

forgot to add qmin to cosmic-pop

---

cosmic/sample/cmc/elson.py
cosmic/sample/cmc/king.py
cosmic/sample/initialcmctable.py
cosmic/sample/sampler/cmc.py
cosmic/sample/sampler/independent.py
cosmic/sample/sampler/multidim.py
cosmic/tests/test_sample.py
examples/CMC_Params.ini

Ok both King and Elson profiles now work and agree with CMC.  King generator is actually *faster* than C code for large clusters.  Also fixed a few typos, created a new sampler (cmc_point_mass) which only does N-body stuff with no stars, and added r_max sampling for binaries (i.e. independent sampler will only sample binaries out to the hard/soft boundary of the cluster).

Fixed Samplers

---

cosmic/sample/cmc/elson.py
cosmic/sample/cmc/king.py

Noticed a stupid mistake in the bisection for the virial radii in the elson sampler.

quick fix to elson sampler

---

cosmic/sample/sampler/cmc.py

Just need to set the virial/tidal radii correctly in both places

Second fix (to CMC point-mass generator)

---

bin/cosmic-pop

was specifying kwarg completely wrong and testing, yet again, only the multidim sampler in my cosmic-pop tests

hotfix to m2min/qmin kwargs
