- cosmic/Match.py
- cosmic/evolve.py
- cosmic/src/const_bse.h
- cosmic/src/evolv2.f
- cosmic/tests/test_match.py
Alright. Now we have an added bcm column which will tell you the current state of the binary: 
bin_state = 0: binary system
bin_state = 1: merged binary through common envelope or through GW radiation
bin_state = 2: disrupted binary 
Since it is in the bcm array, it will be logged at every time step, even when dtp is set by the user.
> Track binary state bcm

- bin/runFixedPop
- cosmic/Match.py
Fixing issue: [#120](https://github.com/COSMIC-PopSynth/COSMIC/issues/120) pointed out by @michaelzevin 
This now tries to use knuth binwidths; and if it can't, uses Scott binwidth. It also catches a warning that gets thrown when log10(0) is calculated for porb=0 sources.
> Convergence fix

- cosmic/evolve.py
- cosmic/src/evolv2.f
- docs/examples/index.rst
- docs/runpop/index.rst
removed merger flag from inputs, now it just gets set at the beginning of evolv2.f to its default value of -1. it still gets used in CMCpass, since we're not sure if it will alter CMC stuff.
> remove merger flag

- cosmic/sample/sampler/independent.py
The previous PR only addressed this for a single binary, which passed all the tests since the tests only work on a single binary for the sampling. we should probably fix that.
> Fixing the orbital period initial sample. 

- cosmic/tests/test_utils.py
- cosmic/utils.py
I ran into this while getting together the LISA DWD models. CO WD progenitors can come from pretty low initial masses in binaries; especially if there is a stable mass transfer phase.
> we were cutting off CO WD progenitors

- cosmic/tests/test_utils.py
- cosmic/utils.py
This address issue #85 
Example of the output working
```
bpp = utils.convert_kstar_evolve_type_to_string(EvolvedBinaryBPP)
```
```
[2 rows x 43 columns]
kstar_1                              kstar_2               evol_type
0                      Hertzsprung Gap                         MS, > 0.7 M⊙            kstar change
0                  Core Helium Burning                         MS, > 0.7 M⊙            kstar change
0  Early Asymptotic Giant Branch (AGB)                         MS, > 0.7 M⊙            kstar change
0  Early Asymptotic Giant Branch (AGB)                         MS, > 0.7 M⊙    supernova of primary
0                         Neutron Star                         MS, > 0.7 M⊙       binary disruption
0                         Neutron Star                         MS, > 0.7 M⊙ …
```
> This integer to string utility is ready to go and has its own unit test

- docs/inifile/index.rst
- examples/Params.ini
This is a one and done commit that simply adds in documentation for the 'convergence_limits' flag.
> had missed adding docs for the convergence limits

- cosmic/evolve.py
- cosmic/tests/test_evolve.py
I added a function _evolve_multi_system which allows binaries to be evolved in batches of size n_per_block, a new optional kwarg for Evolve. Using this function removes the limit on Nstep of approximately 30000 set by the maximum size of the Multiprocessing queue. For example, with n_per_block=200, the limit on the number of systems per step becomes 6000000. The output processing which occurs every Nstep systems is extremely wall-time intensive on a supercomputer, partly because it takes place on only a single core, such that the limitation of ~30000 systems is a major performance bottleneck when running a large number of systems. This function significantly improves the practicability of evolving 100s of millions of systems on a supercomputer. 
I have also added appropriate test cases to …
> added _evolve_multi_system

- cosmic/src/concatkstars.f
Just a quick change to make it easier to compile CMC with multiple fortran/conda environments (and to not write random strings in CMC)
> Quick concatkstars flag

- .travis.yml
- cosmic/src/bpp_array.f
- cosmic/tests/test_utils.py
- cosmic/utils.py
The simplest way to make sure that porb is written properly is to compute it just before you write. Tests have been updated since the wrong porb was written.
> porb write bug

- cosmic/plotting.py
Because the plotting scripts set dtp to 0.01, if you wanted to plot the evolution of binaries for longer than 200 Myr, it broke. The update allows for one to plot for longer times, with a resolution of 10,000 steps.
> Plot scripts

- cosmic/src/evolv2.f
- cosmic/utils.py
- docs/inifile/index.rst
- examples/Params.ini
This is pretty simple. I added the prescriptions detail in Section 5.1 of the StarTrack paper: https://ui.adsabs.harvard.edu/abs/2008ApJS..174..223B/abstract 
This is now qcflag = 4. For WDs, we use the same qcrit as BSE since StarTrack does some more fancy WD stuff than we do right now.
I also took out the overly harsh error check that didn't allow you to specify a single qcrit array change.
Params.ini and docs are updated.
> Qcflag wrapup

- bin/cosmic-pop
- cosmic/sample/sampler/independent.py
- cosmic/tests/test_sample.py
- cosmic/utils.py
- examples/Params.ini
This PR incorporates new initial condition models for the independent sampler by request of @michaelzevin (but really everyone).
Some notes: 
- we adopt the methods of Renzo+2019 which assumes flat in log for m1 < 15 Msun and the power law for m1 >= 15 Msun. This is because the sana+2012 paper focused on *massive* stars
- the Sana+2012 observations for eccentricities are also for massive stars, which might circularize quite a bit from pre-ZAMS interactions since they are close.... thus the eccentricity is pretty severely peaked toward 0.0; for this reason, I recommend that we don't use sana12 as an ecc default for all types of stars.
tests should all be updated!
> Sana initial conditions

- cosmic/src/evolv2.f
This was solved by adding in a write bpp to account for end of RLO forr post CE binaries that enter a CE as a result of contact
Thanks to Zevin for pointing this out in issue #343
> Write end of RLO to bpp after CE caused by contact

- cosmic/src/evolv2.f
Changing coefficient from 1e7 to 3.31e7 which is the correct conversion to put t_KH in units of solar mass, solar radius, solar luminosity.
> correcting the coefficient for tKH

- bin/cosmic-pop
this is needed because the bcm wasn't filtering the different STF histories.
> fixing dtp filter for bcm array

- cosmic/sample/sampler/cmc.py
Slight adjustment to the total mass of cluster hdf5's generated for CMC.  Doesn't change any underlying physics, just agrees better with CMC's code  units for mass
> quick fix to point-mass CMC sampler

- cosmic/utils.py
For the independent sampler, removes the need for a bunch of the COSMIC specific dictionary entries in the ini files (e.g. "convergence", "sampling", etc).
> quick fix for CMC

- cosmic/sample/sampler/cmc.py
- cosmic/sample/sampler/independent.py
Somewhat large commit that still needs some testing, but is pretty critical for CMC.  Two major changes to the independent sampler:
1. Adds a new flag to the independent sampler,  `sample_porb_first`, which if true will sample the orbital periods *before* the eccentricities.  This is somewhat necessary to prevent pathologically large eccentricities (e=0.999) that will come from the thermal distribution, and often place stars inside one another.  This breaks CMC, but is also unphysical for isolated binaries.  If this option is selected, the radii for Roche Lobe overflow are still computed with the orbits, but they are returned and used to truncate the eccentricity distribution (if it is not selected, then the eccentricities are sampled first, and the orbital periods are selected s.t. none …
> changes to the independent sampler

- cosmic/src/kick.f
This small change fixes a (not-so) edge case. When both SNe have kicks of 0.0 (which is common for BBHs), the x_tilt that is calculated for the second SN is 0 since the angle between the angular momentum vectors is 0. When omega2 is then calculated, we get a divide by zero in a trigonometric function that leads to the NaN value in kick_info. 
I just added a simple if/else to address this edge case (setting omega2 to 0). I checked that [multiple binaries example on the Docs](https://cosmic-popsynth.github.io/COSMIC/examples/index.html#multiple-binaries) and it seems to have fixed things.
> fixing NaN that appear for second omega angle

- cosmic/sample/sampler/cmc.py
need to switch kwargs.pop to kwargs.get, since the virial radius was used in multiple places.
> Critical Fix to virial radii

- cosmic/src/hrdiag.f
Addressing #432 
There seemed to be some adjustments to the Fryer fallback models for low core mass stars. I've changed so that it now follows Fryer+2012 directly, and also properly accounts for ECSN (including checking ecsn_mlow, which it wasn't doing before).
> ecsn fixes to fallback prescriptions
